import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className=' text-3xl font-bold text-red-500'>Header</header>
        {children}
        <footer className='text-2xl font-bold text-red-500'>Footer</footer>
      </body>
    </html>
  )
}
